### ISSUE TITLE
Perbaikan Page Hero

### ISSUE THREAD

**Issue by putupradnya** [astarica/jasmine#35]
penambahan animasi the wedding
Tanggal diganti jadi format Hari, Tanggal, contoh: Senin, 31 Mei 2025
intro undangan juga diperbaiki

![image](https://user-images.githubusercontent.com/25524439/120113543-29cd0a00-c1a5-11eb-8603-2bca3fcd7b28.png)

---

## Todo
- [x] Format tanggal dddd, DD MMMM YYYY
- [x] Update intro gretting
- [ ] ~Animation on wedding title~

**Comment by mwafa** [comment]
@putupradnya nama animasina apa tu?

**Comment by mwafa** [comment]
> @putupradnya nama animasina apa tu?

https://codemyui.com/tag/text-animation/

hand writing
